### ISSUE TITLE
Using own dataset

### ISSUE THREAD

**Issue by CherniGhassen** [3dlg-hcvc/mirror3d#3]
Hi, 

I am trying to use mirror3d with my own dataset, I have depth and RGB images and I just want to use the inference part  with the pre-trained weights. Is there a straighforwad way to do it? From what I saw I have to modify a lot in the code before being able to do that, am I missing something?

Thank you!

**Comment by ChristinaTan0704** [comment]
Hi,
Thanks for reaching out. Since our code is based on [Detectron2](https://github.com/facebookresearch/detectron2). To use your own dataset, you need to make some changes to the dataset part. For example, change the code under mirror3d/mirror3dnet/mirror3d_lib/data/datasets. 
Best,
Jiaqi
