### ISSUE TITLE
DeepCompletionRelease unavailable

### ISSUE THREAD

**Issue by kopetri** [3dlg-hcvc/mirror3d#4]
Hello,

The data belonging to [DeepCompletionRelease](https://github.com/yindaz/DeepCompletionRelease) was accidentally deleted.
Do you still have their Matterport3D rendered depth maps?

Please, I would like to benchmark Mirror3D using our approach.

Thank you very much!

**Comment by ChristinaTan0704** [comment]
Hi,
Have you acquired a Matterport3D licence? I can send you a backup of the data once you receive the license.
Best,
Jiaqi

**Comment by kopetri** [comment]
> Hi, Have you acquired a Matterport3D licence? I can send you a backup of the data once you receive the license. Best, Jiaqi

I sent you the license via mail. Thank you!
